### PR TITLE
Fix panic when not using a 2FA token

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ShadiestGoat** [comment]
Hey! Thank you for your intrest, however, verification of the token is already present, its just that its in a bit of a weird spot (first line of the main fetching func, `ConfigType.checkToken()`). 

I put it there because then I could be using the `discordRequest()` function (for consistency mainly), but it does the same thing as your `VerifyToken()`. In the next commit I'll def be moving some of the funcs around so maybe it'll we called in the loading stage, as it makes more sense to do it there. 

Can you elaborate a bit more on the 2FA token thing? What do you mean by that? is `mfa` prefix only for 2fa users?

**Comment by ShadiestGoat** [comment]
Ah thank you, check out the latest commit (0527fd75227dbb38478d585f4875b5bd0ce15450), I have removed panic on non 2fa tokens. Its a shame there isn't a user token prefix ://

**Comment by bytixo** [comment]
sorry for answering this late, and yeah removing the panic is still good since it will panic on other requests because bot tokens are not allowed to use user endpoints

**Comment by ShadiestGoat** [comment]
Bots also can't acceess any further back than weeks so

**Pull request closed without merging**
